# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 845c3fd331cdb844a01335b43aa8ccbfa08cbfc8c32ee3472a84dd9fbbee3521a70613142356b309b6eac9930c50a6449ede8c66472cab585cf161543ffa163a

test:
  secret_key_base: 820dc48d7449458da8a222126261a234bcf5147b50f79d411b7c3f0da605fda2cfebe88b80621aa6a61fa77e0c705c1423ec215a39ab4fcce0cfd303371b115c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
